# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DynamicFlow
                                 A QGIS plugin
 Dynamic is a qgis plugin to estimate the spatio-temporal 3D gradient flow from the point observation of the attributes values such as aggregated cell-phone mobility data. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-03-28
        copyright            : (C) 2024 by Bo-Cheng Lin, Chen-Yu Liu, Ta-Chien Chan
        email                : tachien@geohealth.tw

 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Bo-Cheng Lin, Chen-Yu Liu, Ta-Chien Chan'
__date__ = '2024-03-28'
__copyright__ = '(C) 2024 by Bo-Cheng Lin, Chen-Yu Liu, Ta-Chien Chan'
import subprocess
from .init_checks import check_and_install_requirements
check_and_install_requirements()

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DynamicFlow class from file DynamicFlow.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #check_and_install_requirements()
    from .dynamic_flow import DynamicFlowPlugin
    return DynamicFlowPlugin()
